### ISSUE TITLE
The label.py don't work

### ISSUE THREAD

**Issue by szuRyan** [sergiomsilva/alpr-unconstrained#10]
Searching for license plates using WPOD-NET
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   240 x  80 x   3   ->   240 x  80 x  32  0.033 BFLOPs
    1 max          2 x 2 / 2   240 x  80 x  32   ->   120 x  40 x  32
    2 conv     64  3 x 3 / 1   120 x  40 x  32   ->   120 x  40 x  64  0.177 BFLOPs
    3 max          2 x 2 / 2   120 x  40 x  64   ->    60 x  20 x  64
    4 conv    128  3 x 3 / 1    60 x  20 x  64   ->    60 x  20 x 128  0.177 BFLOPs
    5 conv     64  1 x 1 / 1    60 x  20 x 128   ->    60 x  20 x  64  0.020 BFLOPs
    6 conv    128  3 x 3 / 1    60 x  20 x  64   ->    60 x  20 x 128  0.177 BFLOPs
    7 max          2 x 2 / 2    60 x  20 x 128   ->    30 x  10 x 128
    8 conv    256  3 x 3 / 1    30 x  10 x 128   ->    30 x  10 x 256  0.177 BFLOPs
    9 conv    128  1 x 1 / 1    30 x  10 x 256   ->    30 x  10 x 128  0.020 BFLOPs
   10 conv    256  3 x 3 / 1    30 x  10 x 128   ->    30 x  10 x 256  0.177 BFLOPs
   11 conv    512  3 x 3 / 1    30 x  10 x 256   ->    30 x  10 x 512  0.708 BFLOPs
   12 conv    256  3 x 3 / 1    30 x  10 x 512   ->    30 x  10 x 256  0.708 BFLOPs
   13 conv    512  3 x 3 / 1    30 x  10 x 256   ->    30 x  10 x 512  0.708 BFLOPs
   14 conv     80  1 x 1 / 1    30 x  10 x 512   ->    30 x  10 x  80  0.025 BFLOPs
   15 detection
mask_scale: Using default '1.000000'
Loading weights from data/ocr/ocr-net.weights...Done!
Performing OCR...
Traceback (most recent call last):
  File "gen-outputs.py", line 30, in <module>
    Lcar = lread(detected_cars_labels)
  File "/home/seemmo/Ryan/ALPR/alpr-unconstrained-master/src/label.py", line 57, in lread
    with open(file_path,'r') as fd:
IOError: [Errno 2] No such file or directory: '/tmp/output/03009_cars.txt'
rm: cannot remove '/tmp/output/*_lp.png': No such file or directory
rm: cannot remove '/tmp/output/*car.png': No such file or directory
rm: cannot remove '/tmp/output/*_cars.txt': No such file or directory
rm: cannot remove '/tmp/output/*_lp.txt': No such file or directory
rm: cannot remove '/tmp/output/*_str.txt': No such file or directory

**Comment by dingning94** [comment]
the same question with you！can you deal with this problem？

**Comment by Yinyf0804** [comment]
try to install h5py, it works for me

**Comment by szuRyan** [comment]
@dingning94 
I have not solved this problem yet.

**Comment by sergiomsilva** [comment]
Looks like the first network failed to find any car in the picture. Can you send the complete log and command line passed?
