### ISSUE TITLE
How can I train my own model?

### ISSUE THREAD

**Issue by beizhengren** [sergiomsilva/alpr-unconstrained#11]
Hi~
Thanks for providing this project, and the effect of recognizing plate license is so good.
Now, I want to train my own weights to detect chinese character, how can I train my own arguments ?
Thanks a lot !

**Comment by sergiomsilva** [comment]
Hi @beizhengren , I will upload here in the future the training script. I hope to do that early this month as I promised in another thread, but unfortunately, I'm a bit out of time right now. So maybe it will be available only at the end of the month.

**Comment by sergiomsilva** [comment]
Code available! Sorry for the delay =P

**Comment by hejinsome** [comment]
@beizhengren 你有标注的中文车牌吗？尤其汉族样本？
