### ISSUE TITLE
keras_util.py reconstruct array operation

### ISSUE THREAD

**Issue by AsharFatmi** [sergiomsilva/alpr-unconstrained#113]
Hi,
I am implementing TensorRT for LP detection.

In src.keras_utils.py file, there is a NumPy array operation that I don't understand what it does.

`Probs = Y[...,0]`

[keras_utils.py](https://github.com/sergiomsilva/alpr-unconstrained/blob/1cf77f16d84d5f6e407cd15afd6bdd76ad4deca4/src/keras_utils.py#L46)

Any idea what this does?

**Comment by muhammadabdullah34907** [comment]
@AsharFatmi Are you able to convert model into tensorRT engine ? Please any help ?
