### ISSUE TITLE
The format of the dataset

### ISSUE THREAD

**Issue by beizhengren** [sergiomsilva/alpr-unconstrained#13]
Hi~
I find the format of ssig, such as Track41[11].txt, as below:

“4,0.173926,0.249481,0.249481,0.173926,0.716426,0.713264,0.761756,0.763864,LP,
4,0.178706,0.187287,0.187287,0.178706,0.729881,0.729557,0.751266,0.751536,P,
……”

Does the first line mean that there are 2 license plates in the image, and "4" represents the class?
But the next line also has a "4", am I understanding correcty?
 
Morever,I find the training set of VOC ( for yolo ) is that 
11 0.344192634561 0.611 0.416430594901 0.262
14 0.509915014164 0.51 0.974504249292 0.972
Now, I want to use the dataset, ssig, to train, should I spilt the data?such as
(x1,y1) = (0.173926, 0.716426)
(x2,y2) = (0.249481, 0.713264)
(x3,y3) = (0.249481, 0.761756)
(x4,y4) = (0.173926, 0.763864)
and convert above coordinates into  VOC format?

Much obiligated!

**Comment by sergiomsilva** [comment]
Hi @beizhengren, answering your questions:

- the 4 at the beginning of each line only means that the annotation has 4 points and is useless in this scenario. The "class" is the last value, for instance, LP means license plate and P means the character P;
- not sure if I fully understand the last question, but yes you can transform the labels to the VOC format by losing some information, i.e., you need to transform the 4 points annotation into a 2.

Regards
