### ISSUE TITLE
Trying to use python3. vehicle-detection.py, line 28, vehicle_net  = dn.load_net(vehicle_netcfg, vehicle_weights, 0) ctypes.ArgumentError: argument 1: wrong type

### ISSUE THREAD

**Issue by alexw22** [sergiomsilva/alpr-unconstrained#136]
I am trying to run:
bash run.sh -i samples/test -o /tmp/output -c /tmp/output/results.csv

Up to now I only have changed the print statements adding parentheses to work in python3.

Now I get the following error:
Traceback (most recent call last):
  File "vehicle-detection.py", line 28, in <module>
    vehicle_net  = dn.load_net(vehicle_netcfg, vehicle_weights, 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

Any ideas as to what might be the issue here?

**Comment by alexw22** [comment]
I have been able to get closer to succes. Look at issue #60 and #106 for more info.

**Comment by yunWJR** [comment]
append .encode('utf-8') after the string,like this

vehicle_weights = "data/vehicle-detector/yolo-voc.weights".encode('utf-8')
