### ISSUE TITLE
About annotations

### ISSUE THREAD

**Issue by umbralada** [sergiomsilva/alpr-unconstrained#15]
Hello, in your file README.txt, which is available at http://www.inf.ufrgs.br/~crjung/alpr-datasets/labels/training-dataset-annotations.zip, the following annotation format

N, tlx, tly, trx, try, brx, bry, blx, bly, LABEL,

where:
N = number or corners (fixed in 4)
tl [x, y] = top left corner
tr [x, y] = top right corner
br [x, y] = bottom right corner
bl [x, y] = bottom left corner

Values from a text file, for example Track43(24)

4,0.881302,0.959447,0.962407,0.881894,0.729750,0.732384,0.781904,0.776635, LP

when multiplied by the corresponding width and height do not give a rectangle.

tlx = 0.881302 * ImageWidth = 1692
tly = 0.959447 * ImageHeight = 1036
trx = 0.962407 * ImageWidth = 1848
try = 0.881894 *  ImageHeight = 952
brx = 0.729750 * ImageWidth = 1401
bry = 0.732384 *  ImageHeight = 791
blx = 0.781904 * ImageWidth = 1501
bly = 0.776635 * ImageHeight = 839

What's my mistake?

**Comment by sergiomsilva** [comment]
Hi @umbralada , I was checking and you are right, the README.txt was wrong. I just corrected.

After N, the first 4 values are the "x"s and the last 4 the "y"s. I altered the description to:

N,tlx,trx,brx,blx,tly,try,bry,bly,LABEL,

Thank you for pointing out this problem! Best regards

**Comment by ganliqiang** [comment]
my god ! the readme is not correct now, i misunderstand in this all afternoon  you make me sad..disappointed

**Comment by sergiomsilva** [comment]
@ganliqiang if you had spent 30 minutes of your afternoon digging into the code you would have noticed. There is a part that draws the LP into the input image, very easy to check from there. Regards.
