### ISSUE TITLE
The function about 'reconstruct' in keras_utils.py

### ISSUE THREAD

**Issue by zrl4836** [sergiomsilva/alpr-unconstrained#21]
Hi！I am reading your code recently.
However, I can't always understand this function, can you tell me more about this? thank you very much!

**Comment by sergiomsilva** [comment]
Hi @zrl4836 , sure! This function is used to interpret the results of the WPOD-NET. Considering a cell whose probability of being a LP is higher than a certain threshold, its affine parameters are used to interpolate that region back to the frontal-plane of a specific size (this interpolated patch is one of the outputs).

Most likely, many cells around the LP will have high probabilities, thus, a non-maximal suppression algorithm is used to filter out overlapping detections. Note that NMS can be easily applied to rectangular regions, but not for arbitrary shapes. Therefore, we consider the smallest rectangle containing the detected shape, which is also calculated inside the function.

I hope that helps.
