### ISSUE TITLE
Error in predict

### ISSUE THREAD

**Issue by linzhi123** [sergiomsilva/alpr-unconstrained#22]
ocr_net  = dn.load_net(ocr_netcfg, ocr_weights, 0)
ArgumentError: argument 1: <class 'TypeError'>: wrong type

What is the reason?

**Comment by USTC-SQQ** [comment]
1、python3-->python2 
2、在Python 2.7中，string默认的是byte-strings，而在 Python 3.x中默认的是unicode。因此在3.x中将string传入到调用的DLL之前先使用 .encode('ascii') 将其变成 byte string类型

**Comment by sergiomsilva** [comment]
I will close the issue assuming it was solved by @USTC-SQQ answer.
