### ISSUE TITLE
0 cars found

### ISSUE THREAD

**Issue by lcaikk1314** [sergiomsilva/alpr-unconstrained#25]
HIi, I meet a problem, someone can help ?

mask_scale: Using default '1.000000'
Loading weights from data/vehicle-detector/yolo-voc.weights...Done!
Searching for vehicles using YOLO...
        Scanning samples/test/03009.jpg
                0 cars found        
Scanning samples/test/03016.jpg
                0 cars found       
 Scanning samples/test/03025.jpg
                0 cars found
        Scanning samples/test/03033.jpg
                0 cars found
        Scanning samples/test/03057.jpg
                0 cars found
        Scanning samples/test/03058.jpg
                0 cars found
        Scanning samples/test/03066.jpg
                0 cars found
        Scanning samples/test/03071.jpg
                0 cars found
Using TensorFlow backend.

**Comment by rochesterlmg** [comment]
@lcaikk1314 ,do you use Python3, does it work well now?

**Comment by kubl88** [comment]
> @lcaikk1314 ,do you use Python3, does it work well now?
for python3, something wrong in this code (vehicle-detection.py):R = [r for r in R if r[0] in ['car','bus']].change or cancel the code.

**Comment by anoob09** [comment]
I am getting the same. 0 cars found in Python 3. Did you solve it?

**Comment by leondgarse** [comment]
Same issue here, solved by modifying vehicle-detection.py, line 48
From:
R = [r for r in R if r[0] in ['car','bus']]
To:
R = [r for r in R if r[0].decode() in ['car','bus']]
