### ISSUE TITLE
where is the wpod_net network,I can not find it

### ISSUE THREAD

**Issue by xiaoxiaotao** [sergiomsilva/alpr-unconstrained#28]
I want to know the wpod_net structure

**Comment by danishansari** [comment]
this is the [paper](http://openaccess.thecvf.com/content_ECCV_2018/papers/Sergio_Silva_License_Plate_Detection_ECCV_2018_paper.pdf) that i found.

**Comment by xiaoxiaotao** [comment]
I find it ,thank you.

**Comment by beizhengren** [comment]
@xiaoxiaotao Have you found the WPOD-NET source code and the detail network structure? Thank you
