### ISSUE TITLE
Can i use it on video too?

### ISSUE THREAD

**Issue by soaka0721** [sergiomsilva/alpr-unconstrained#32]
Can i use it on video too?
I think it would be possible if vehicle -detection.py, license-plate-detection.py, and license-plate-ocr.py were combined and the image input change like video demo.py from oiginal yolo.

Is there anything that can help?

**Comment by Ruveyda** [comment]
hi. @soaka0721 . did you try to use it on video? can you share your experience with us? thanks.

**Comment by Programmerwyl** [comment]
I successfully run it on video， I use 2 different frameworks (Darknet and Keras).
Just extract the method of loading the model to the outermost and it works
