### ISSUE TITLE
Bounding box on license plates

### ISSUE THREAD

**Issue by FilipaRamos** [sergiomsilva/alpr-unconstrained#33]
Hi! I was trying to get a bounding box surrounding the license plates that were found on the image. Could you please explain the output of the model that detects license plates? I also do not understand the reconstruct function too well, if you could give some input on this as well it would be really helpful.

Thanks a lot in advance!

**Comment by sergiomsilva** [comment]
Hi @FilipaRamos , the model output parameters for an affine transformation centred in the feature cell. I suggest you take a look at the paper for a detailed explanation. Having the affine transformation, you can interpolate the LP region into a new image that will be used to feed the OCR network. This is the role of the reconstruction function.
