### ISSUE TITLE
About wpod-net training

### ISSUE THREAD

**Issue by beizhengren** [sergiomsilva/alpr-unconstrained#48]
Hello,
1. Is the trian-detector using for traing WPOD-NET, the second stage in this project?
2. Wheather the training result generated by train-detector include the trasformation information?
when we using the training result by run.sh, has the output plate-position rectified by Affine Transformation
Matrix?
Thank you all!

**Comment by IbrahimBond** [comment]
@beizhengren  do you know the answer to your second question? how is the license rectified and what part of the code is responsible for it? 

thanks
