### ISSUE TITLE
About train code

### ISSUE THREAD

**Issue by CaptainEven** [sergiomsilva/alpr-unconstrained#5]
Is there any train code about the WPOD-NET?  I'll be very grateful if provided.

**Comment by sergiomsilva** [comment]
Hi @CaptainEven , it will be available in a week. Thanks for the interest.

**Comment by CaptainEven** [comment]
@sergiomsilva Oh, that's great!

**Comment by sergiomsilva** [comment]
Sorry, some urgent work appeared for me and I had no time to deal with this part yet. But I will try to upload later this month.

**Comment by wmn931201** [comment]
Thank you for replying!

**Comment by sergiomsilva** [comment]
Code available now!

**Comment by wmn931201** [comment]
@sergiomsilva Thank you so much!
