### ISSUE TITLE
Is it possible to train LP detector on GPU?

### ISSUE THREAD

**Issue by Ruveyda** [sergiomsilva/alpr-unconstrained#56]
Hi,

I start to train my own licence plates. but it seems this will take very long time. (21 days according to my calculations). I use this command 

`python train-detector.py --model models/eccv-model-scracth --name my-trained-model --train-dir samples/train-detector --output-dir models/my-trained-model/ -op Adam -lr .001 -its 300000 -bs 64`

Should I do `its = 100000` and `bs = 32` ? Or maybe less.

Or is it possible to use GPU?

What do you suggest?

Thanks.

**Comment by Harsha-1729** [comment]
Hello Ruveyda,

I am also planning to train the network with my own license plates, Could you please let me know how did you proceed?

Thanks

**Comment by littlerain2310** [comment]
> Hello Ruveyda,
> 
> I am also planning to train the network with my own license plates, Could you please let me know how did you proceed?
> 
> Thanks

Hi you can train it with gpu when you can set up your tensorflow works with GPU. I follow [this instruction](https://www.tensorflow.org/install/pip)
