### ISSUE TITLE
Description of data inside "*_lp.txt"

### ISSUE THREAD

**Issue by amit2319** [sergiomsilva/alpr-unconstrained#6]
_licence-plate-detection.py_ returns ***_lp.png**  &  ***_lp.txt**,
can you describe data inside ***_lp.txt**.

sample data:
`4,0.864626,0.946707,0.937679,0.855598,0.571571,0.515678,0.573691,0.629584,,`

**Comment by inamesion** [comment]
4 is class
0.864626,0.946707,0.937679,0.855598,0.571571,0.515678,0.573691,0.629584, is the axis of  four point of license plate after Normalizition

**Comment by amit2319** [comment]
I want to map these 4 points on the input image of _licence-plate-detection.py_.
Any help, I have tried _x*width(img)_ and _y*height(img)_ but points doesn't match the actual license plate.

**Comment by sergiomsilva** [comment]
@amit2319 these points are related to the cropped car image, not to the original image. You need to multiply by the width and height of the car bounding-box, and sum the top-left offset to retrieve the points in the original image space.

**Comment by amit2319** [comment]
@sergiomsilva  actually I was trying to retrive license plate from car_bounding_box only, but  _x.width(img) and y.height(img)_ where img refers to image of  car_bounding-box doesn't reproduce the results.

In following data:
`4,0.864626,0.946707,0.937679,0.855598,0.571571,0.515678,0.573691,0.629584,,`
(x1,y1) = (0.864626,0.946707)
(x2,y2) = (0.937679,0.855598)
(x3,y3) = (0.571571,0.515678)
(x4,y4) = (0.573691,0.629584)

Am I interpreting it right?

**Comment by sergiomsilva** [comment]
Ah ok... now I understood. Its not the correct intepretation, considering your notation, the correct should be:

(x1,y1) = (0.864626, 0.571571)
(x2,y2) = (0.946707, 0.515678)
(x3,y3) = (0.937679, 0.573691)
(x4,y4) = (0.855598, 0.629584)

In summary, the first 4 values are the x's, and the next 4, the y's.

**Comment by amit2319** [comment]
@sergiomsilva  Thanks! it worked.
