### ISSUE TITLE
using python3

### ISSUE THREAD

**Issue by Ruveyda** [sergiomsilva/alpr-unconstrained#60]
Hi, I use python 3 in this project. for that I made some changes for car detection:

        vehicle_weights = bytes("data/vehicle-detector/yolo-voc.weights", encoding="utf-8")
        vehicle_netcfg = bytes("data/vehicle-detector/yolo-voc.cfg", encoding="utf-8")
        vehicle_dataset = bytes("data/vehicle-detector/voc.data", encoding="utf-8")

No error while working, but : 

> Searching for vehicles using YOLO...
> 	Scanning ./test/0010.jpg
> 		0 cars found
> 	Scanning ./test/0017.jpg
> 		0 cars found
> 	Scanning ./test/12.jpg
> 		0 cars found
> 	Scanning ./test/13.jpg
> 		0 cars found

It could not find any car. Where am i wrong? thank you.

**Comment by virtualenv** [comment]
Did you solve this issue ?

**Comment by Ruveyda** [comment]
yes. I used Python wrapper. https://github.com/madhawav/YOLO3-4-Py 
@virtualenv

**Comment by kelvin-jose** [comment]
Using the above given wrapper, the code is executing perfectly.

**Comment by divyang805** [comment]
Hello @Ruveyda and @kelvin-jose please and @virtualenv  can you tell me about above rapper and mainly how to use it i dont have much knowledge about yolo and opencv so any help would be appreciated.

**Comment by kelvin-jose** [comment]
first,
pip install yolo34py

then update the lines 24,25 and 26 of license-plate-ocr.py to

   ```
 vehicle_weights = bytes("data/vehicle-detector/yolo-voc.weights", encoding="utf-8")
 vehicle_netcfg = bytes("data/vehicle-detector/yolo-voc.cfg", encoding="utf-8")
 vehicle_dataset = bytes("data/vehicle-detector/voc.data", encoding="utf-8")
```

**Comment by timtensor** [comment]
Hi , I am using virtual envitoment to setup the above repository. i seem to get an error on running into a couple of issues and wondering what to change . I changed the above mentioned changes in the files in` vehicles-detection.py` and `license-plate-ocr.py` with the following in lines 24,25,26 in both the files 
   ```
 vehicle_weights = bytes("data/vehicle-detector/yolo-voc.weights", encoding="utf-8")
    vehicle_netcfg = bytes("data/vehicle-detector/yolo-voc.cfg", encoding="utf-8")
    vehicle_dataset = bytes("data/vehicle-detector/voc.data", encoding="utf-8")
```
Is there any other places where changes have to be made in order to run in python3 ? I have the following packages installed . 

```
Keras (2.3.1)
numpy (1.18.2)
opencv-python (4.2.0.32)
tensorflow (1.5.0)
yolo34py (0.1rc12)
numpy (1.18.2)

```

**Comment by kelvin-jose** [comment]
> Hi , I am using virtual envitoment to setup the above repository. i seem to get an error on running into a couple of issues and wondering what to change . I changed the above mentioned changes in the files in` vehicles-detection.py` and `license-plate-ocr.py` with the following in lines 24,25,26 in both the files
> 
> ```
> vehicle_weights = bytes("data/vehicle-detector/yolo-voc.weights", encoding="utf-8")
>  vehicle_netcfg = bytes("data/vehicle-detector/yolo-voc.cfg", encoding="utf-8")
>  vehicle_dataset = bytes("data/vehicle-detector/voc.data", encoding="utf-8")
> ```
> 
> Is there any other places where changes have to be made in order to run in python3 ? I have the following packages installed .
> 
> ```
> Keras (2.3.1)
> numpy (1.18.2)
> opencv-python (4.2.0.32)
> tensorflow (1.5.0)
> yolo34py (0.1rc12)
> numpy (1.18.2)
> ```

What kind of error are you getting there? Do you have the traceback of the error?
