### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by laoshuai** [sergiomsilva/alpr-unconstrained#7]
$ bash run.sh samples/ /tmp/output /tmp/output/results.csv
Press any key to continue...
run.sh: 行 71:  2956 Segmentation fault      python vehicle-detection.py $1 $2
Using TensorFlow backend.
Traceback (most recent call last):
  File "license-plate-detection.py", line 5, in <module>
    from src.keras_utils                        import load_model
  File "D:\cywin\home\Administrator\alpr\src\keras_utils.py", line 6, in <module>
    from label import Label
ImportError: No module named 'label'
run.sh: 行 77:  7916 Segmentation fault      python license-plate-ocr.py $2
Traceback (most recent call last):
  File "gen-outputs.py", line 7, in <module>
    from src.utils                                      import crop_region, image_files_from_folder
  File "D:\cywin\home\Administrator\alpr\src\utils.py", line 7, in <module>
    from label import Label
ImportError: No module named 'label'
rm: 无法删除'/tmp/output/*_lp.png': No such file or directory
rm: 无法删除'/tmp/output/*car.png': No such file or directory
rm: 无法删除'/tmp/output/*_cars.txt': No such file or directory
rm: 无法删除'/tmp/output/*_lp.txt': No such file or directory
rm: 无法删除'/tmp/output/*_str.txt': No such file or directory

**Comment by wmn931201** [comment]
Modify "from label import Label" to "from src.label import Label"
