### ISSUE TITLE
i want to make my own ocr data providing from image plate. How do you make labelising please

### ISSUE THREAD

**Issue by bakaryfayad** [sergiomsilva/alpr-unconstrained#70]
this program doesn't work very well in my case. I would want to retrain the ocr data with my own image plate. But i don't know how to labelize my images for character detection. I used labelimg but didn't work. Can you help me please!!

**Comment by li675599061** [comment]
labImage

**Comment by bakaryfayad** [comment]
@li675599061  where can I found it please

**Comment by li675599061** [comment]
Maybe you can refer to this website: https://blog.csdn.net/qq_34484472/article/details/73135354#reply

**Comment by li675599061** [comment]
labelImg:https://blog.csdn.net/learning_tortosie/article/details/80947301

**Comment by bakaryfayad** [comment]
okey fine.it's what I was talking about. Thanks you
