### ISSUE TITLE
The license-plate-ocr.py don't work

### ISSUE THREAD

**Issue by 245003478** [sergiomsilva/alpr-unconstrained#9]
when i am running the test, vehicle-detection.py and licendr-plate-detection.py is ok but license-plate-ocr.py can't recognize character (python3 and opencv3.4)
I got this:
mask_scale: Using default '1.000000'
Loading weights from data/ocr/ocr-net.weights...Done!
Performing OCR...
	Scanning ./tmp/output/03058_1car_lp.png
No characters found
	Scanning ./tmp/output/03071_0car_lp.png
No characters found
	Scanning ./tmp/output/03057_0car_lp.png
No characters found
	Scanning ./tmp/output/03009_0car_lp.png
No characters found
	Scanning ./tmp/output/03016_0car_lp.png
No characters found
	Scanning ./tmp/output/03066_1car_lp.png
No characters found
	Scanning ./tmp/output/03033_0car_lp.png
No characters found
	Scanning ./tmp/output/03025_0car_lp.png
No characters found

**Comment by 245003478** [comment]
@zoidburg 
Thanks a lot, it worked!

**Comment by sergiomsilva** [comment]
Just updated the network descriptor with the correction mentioned in #4 . Thanks.
